name: bucketeer_flutter_client_sdk
description: Bucketeer
version: 0.0.1 # x-release-please-version
homepage: https://bucketeer.io/
repository: https://github.com/bucketeer-io/flutter-client-sdk
documentation: https://docs.bucketeer.io/sdk/client-side/flutter
issue_tracker: https://github.com/bucketeer-io/flutter-client-sdk/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  mocktail: ^0.3.0

flutter:
  plugin:
    platforms:
      android:
        package: io.bucketeer.sdk.flutter
        pluginClass: BucketeerFlutterClientSdkPlugin
      ios:
        pluginClass: BucketeerFlutterClientSdkPlugin
