enum CallMethods {
  initialize,
  stringVariation,
  intVariation,
  doubleVariation,
  boolVariation,
  jsonVariation,
  track,
  currentUser,
  updateUserAttributes,
  fetchEvaluations,
  flush,
  evaluationDetails,
  addProxyEvaluationUpdateListener,
  destroy,
  unknown,
}
