name: Build and run unit tests

on:
  push:
    branches:
      - main
      - feat/ci-cd-update
    paths-ignore:
      - "*.md"
  workflow_dispatch:
  workflow_call:

concurrency:
  group: release-build-${{ github.ref }}
  cancel-in-progress: true

env:
  FLUTTER_VERSION: "3.24.3"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: /opt/hostedtoolcache/flutter # For Ubuntu machine
          key: ${{ runner.os }}-flutter-install-cache-${{ env.FLUTTER_VERSION }}

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@f2c4f6686ca8e8d6e6d0f28410eeef506ed66aff # v2.18.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run unit tests
        run: make unit-test

  build-example-app-android:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: /Users/runner/hostedtoolcache/flutter # For mac OS
          key: ${{ runner.os }}-flutter-install-cache-${{ env.FLUTTER_VERSION }}

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@f2c4f6686ca8e8d6e6d0f28410eeef506ed66aff # v2.18.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build the example app
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx1536m -XX:MaxMetaspaceSize=2g"
        run: |
          make build-android

  build-example-app-ios:
    runs-on: macos-15-xlarge
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: /Users/runner/hostedtoolcache/flutter # For mac OS
          key: ${{ runner.os }}-flutter-install-cache-${{ env.FLUTTER_VERSION }}

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@f2c4f6686ca8e8d6e6d0f28410eeef506ed66aff # v2.18.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Build the example app
        run: |
          make build-ios
