name: Publish to pub.dev

on:
  push:
    tags:
      - v*
    branches:
      - initial-implementation

env:
  FLUTTER_VERSION: 3.13.1

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter # For Ubuntu machine
          key: ${{ runner.os }}-flutter-install-cache-${{ env.FLUTTER_VERSION }}

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa # v2.10.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      # This is a workaround to ensure that we don't publish to Cocoapods before the Build and Integration tests workflow is finished.
      - name: Wait for Android Integration tests
        if: ${{ ! github.event.inputs || github.event.inputs.skip_release_note == 'false' }}
        uses: lewagon/wait-on-check-action@e106e5c43e8ca1edea6383a39a01c5ca495fd812 # v1.3.1
        with:
          ref: ${{ github.ref }}
          # DO NOT CHANGE the check-name. This name is based on the workflow job name and the matrix device defined in the build.yaml
          check-name: "android-integration-test (33)"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Wait for iOS Integration tests
        if: ${{ ! github.event.inputs || github.event.inputs.skip_release_note == 'false' }}
        uses: lewagon/wait-on-check-action@e106e5c43e8ca1edea6383a39a01c5ca495fd812 # v1.3.1
        with:
          ref: ${{ github.ref }}
          # DO NOT CHANGE the check-name. This name is based on the workflow job name and the matrix device defined in the build.yaml
          check-name: "ios-integration-test (iPhone 14 Simulator (16.2))"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Publish
        run: flutter pub publish --dry-run
