name: Publish manually to pub.dev

on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.19.2"

jobs:
  publish:
    permissions:
      id-token: write # This is required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: /opt/hostedtoolcache/flutter # For Ubuntu machine
          key: ${{ runner.os }}-flutter-install-cache-${{ env.FLUTTER_VERSION }}

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa # v2.10.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Setup credentials
        run: |
          mkdir -p ~/.config/dart
          cat <<EOF > ~/.config/dart/pub-credentials.json
          ${{ secrets.PUB_DEV_CREDENTIALS_JSON }}
          EOF

      - name: Publish
        run: flutter pub publish --force
