name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/release-please-action@4c5670f886fe259db4d11222f7dff41c1382304d # v3.7.12
        with:
          changelog-types: |
            [
              {"type":"build","section":"Build System","hidden":false},
              {"type":"chore","section":"Miscellaneous","hidden":false},
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"perf","section":"Performance Improvements","hidden":false},
              {"type":"refactor","section":"Code Refactoring","hidden":false},
              {"type":"revert","section":"Reverts","hidden":false}
            ]
          release-type: dart
          include-v-in-tag: false
          release-as: 0.0.3
          extra-files: |
            pubspec.yaml
            android/build.gradle
            ios/bucketeer_flutter_client_sdk.podspec
          token: ${{ secrets.WORKFLOW_TOKEN }} # We need to set the PAT so the publish workflow can be triggered
